config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:new]
  resources :articles
  resources :visitors
  resources :categories, except: [:destroy]
  # resources :sessions
  root to: 'visitors#index'
  get 'articles/index'
  get 'articles/new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10}
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: {in: 3..25}
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :articles, dependent: :destroy
  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { in: 3..25 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: EMAIL_REGEX }
  before_save do
    self.email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  expose :articles, ->{ Article.all }
  expose :article

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
    @categories = Category.all
  end

  def new
    @article = Article.new

  end

  def edit

  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show

  end

  def destroy
    @article.destroy
    flash[:danger] = "Article was successfully obliterated"
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def require_same_user
    if current_user != @article.user and !current_user.admin?
      flash[:danger] = "You can only edit or delete your own articles"
      redirect_to  root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was created successfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category name was successfully updated"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? and !current_user.admin?)
      flash[:danger] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "You have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "Invalid credentials please try again"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You are now logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update]
  before_action :require_admin, only: [:destroy]
  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the alpha blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your profile was successfully updated"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles have been deleted"
    redirect_to users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger] = "You can only edit your own account"
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only administraors can perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    @articles = Article.last(2)
    redirect_to articles_path if logged_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<% obj.each do |a| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to a.title, article_path(a) %>
        </div>
        <div class="article-body">
          <%= truncate(a.description, length: 100) %>
          <div class="article-meta-details">
            <small>Created by:<%= a.user.username if a.user %>,
              <%= time_ago_in_words(a.created_at) %> ago,
                last updated: <%= time_ago_in_words(a.updated_at) %>
            </small>
          </div>
        </div>
        <% if a.categories.any? %>
          <p>Categories: <%= render a.categories %></p>
        <% end %>
        <% if logged_in? && (current_user == a.user || current_user.admin?) %>
            <div class="article-actions">
              <%= link_to "Edit this article", edit_article_path(a), class: "btn btn-xs btn-primary" %>
              <%= link_to "Delete this article", article_path(a), method: :delete,
              data: { confirm: "Are you sure you want to delete this article?" }, class: "btn btn-xs btn-danger" %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter title", autofocus: true %>

    <%= f.label :description %>
    <%= f.text_area :description, rows: 10, class: 'form-control', placeholder: "Enter a description of the article" %>

    <div class="row">
      <div class="col-sm-offset-2 col-sm-8">
        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
          <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
        <% end %>
      </div>
    </div>
    <%= f.submit class: "btn btn-primary btn-lg btn-block", id: "edit-btn" %>
    <% end %>
  </div>
</div>
<div class="text-center" id="edit-cancel">
  [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
</div>

app/views/articles/edit.html.erb
<%= render 'shared/errors', obj: @article%>
<% provide(:title, "Edit article") %>
<h1 class="text-center">Edit article</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@article) do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>

    <%= f.label :description %>
    <%= f.text_area :description, rows: 10, class: 'form-control' %>

    <div class="row">
      <div class="col-sm-offset-2 col-sm-8">
        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
          <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
        <% end %>
      </div>
    </div>

    <%= f.submit "Save changes", class: "btn btn-primary btn-lg btn-block", id: "edit-btn" %>
    <% end %>
  </div>
</div>
<div class="text-center" id="edit-cancel">
  [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
</div>

app/views/articles/index.html.erb
<div class="container">
<% @articles.each do |a| %>
    <!--Main layout-->
    <div class="container">
        <div class="row">

            <!--Main column-->
            <div class="col-lg-8">

                <!--Post-->
                <div class="post-wrapper">
                    <!--Post data-->
                    <h1 class="h1-responsive"><%= link_to a.title, article_path(a) %></h1>
                    <h3 id="author">Written by <%= a.user.username if a.user %></h3>, <h4 id="time"> <%= time_ago_in_words(a.created_at) %> ago</h4>
                    <br>
                    <!--Featured image -->
                    <div class="view overlay hm-white-light z-depth-1-half">
                        <img src="https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.bahamas.com%2Fsites%2Fdefault%2Ffiles%2Fstyles%2Fmedia_resources_fullwidth%2Fpublic%2Fmedia%2Fresources%2Fjunkanoo_summer_festival_july_18_2015_87485.jpg%3Fitok%3DQWyAmLMG&f=1" class="img-fluid " alt="">
                        <div class="mask">
                        </div>
                    </div>

                    <br>

                    <!--Post excerpt-->
                    <p><%= truncate(a.description, length: 400) %></p>
                    <!--"Read more" button-->
                    <button class="btn btn-primary">Read more</button>
                </div>
                <!--/.Post-->
                <br><br>
                <hr>

            </div>
            <!--Sidebar-->
            <div class="col-lg-4">
              <% if article.categories.any? %>
                <% @categories.each do |cat| %>
                  <div class="widget-wrapper">
                    <br>
                      <h4>Categories:</h4>
                      <div class="list-group">
                          <%= cat.categories.name %>
                      </div>
                  </div>
                <% end %>
              <% end %>


                <!-- <div class="widget-wrapper">
                    <h4>Subscription form:</h4>
                    <br>
                    <div class="card">
                        <div class="card-block">
                            <p><strong>Subscribe to our newsletter</strong></p>
                            <p>Once a week we will send you a summary of the most useful news</p>
                            <div class="md-form">
                                <i class="fa fa-user prefix"></i>
                                <input type="text" id="form1" class="form-control">
                                <label for="form1">Your name</label>
                            </div>
                            <div class="md-form">
                                <i class="fa fa-envelope prefix"></i>
                                <input type="text" id="form2" class="form-control">
                                <label for="form2">Your email</label>
                            </div>
                            <button class="btn btn-primary">Submit</button>

                        </div>
                    </div>
                </div>

            </div> -->
            <!--/.Sidebar-->
        </div>
    </div>
    <!--/.Main layout-->

</div>
<% end %>
<!--Pagination-->
<nav class="text-xs-center">
    <p><%= will_paginate %></p>
</nav>
<!--/.Pagination-->
<!--Footer-->

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/show.html.erb
<h1 class="text-center">Title: <%= @article.title %></h1>
<div class="well col-xs-8 col-xs-offset-2">
  <% if @article.user %>
  <ul class="listing">
    <div class="row text-center">
      <div class="col-md-4 col-md-offset-4">
        <li>Created by:</li>
        <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
        <li class="article-title">
          <%= link_to @article.user.username, user_path(@article.user) %>
        </li>
        <li><small>
          <%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
        </small></li>
      </div>
    </div>
  </ul>
  <% end %>
  <h4 class="text-center description"><strong>Description:</strong></h4>
  <hr>
  <%= simple_format(@article.description) %>
  <% if @article.categories.any? %>
    <p>Categories: <%= render @article.categories %></p>
  <% end %>
  <div class="article-actions">
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
    <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
    <%= link_to "Delete this article", article_path(@article), method: :delete,
    data: { confirm: "Are you sure you want to delete this article?" }, class: "btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %> &nbsp;</span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<% provide(:title, "New Category") %>


  <div class="text-center ">
    <%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter category name", autofocus: true %>

    <%= f.submit class: "btn btn-primary btn-lg btn-block", id: "edit-btn" %>
    <% end %>
  </div>

<div class="text-center" id="edit-cancel">
  [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
</div>

app/views/categories/edit.html.erb
<h1 class="text-center">Edit Category Name</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-center">All Categories</h1>
<div class="text-center">
  <%= will_paginate %>
  <% @categories.each do |category| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4-offset-4">
          <li class="article-title">
            <%= link_to "#{category.name}", category_path(category) %>
          </li>
          <li><small><%= pluralize(category.articles.count, "article")%></small></li>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<% provide(:title, "New Category") %>
<h1 class="text-center">Create New Category</h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<% provide(:title, "Categories") %>
<h1 class="text-center"><%= "Category: " + @category.name %></h1>
<div class="text-center">
  <% if logged_in? and current_user.admin? %>
    <div class="row">
      <span class="badge"><%= link_to "Edit Category Name", edit_category_path(@category) %></span>
    </div>
    <% end %>
  <%= will_paginate @category_articles %>
</div>
<%= render 'articles/article', obj: @category_articles %>
<div class="text-center">
  <%= will_paginate @category_articles %>
</div>

app/views/layouts/_footer.html.erb
<div class="container foot">
  <footer class="footer">
    <small>
      Copyright &copy; <a href="https://warm-mountain-91570.herokuapp.com/" target="_blank">Ruby on Rails Developer</a>
      by <a href="https://github.com/cwilliams3579" target="_blank">Cleveland Williams</a>
    </small>
    <nav>
      <ul>
        <li><%= link_to 'About', page_path('about') %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <i class="fa fa-commenting-o fa-2x" aria-hidden="true"></i>
      <%= link_to "Blogger Spot", root_path, class: "navbar-brand", id: "logo" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to 'Users', users_path %></li>
        <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New Article", new_article_path %></li>
          </ul>
        </li>
        <%  end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Categories", categories_path %></li>
            <% Category.all.each do |category| %>
              <li><%= link_to "#{category.name}", category_path(category) %></li>
            <% end %>
            <% if logged_in? and current_user.admin %>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Create New Category", new_category_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li><%= link_to "Log out", logout_path, method: :delete, data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Logging out..."} %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <%= "Admin" if current_user.admin? %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>
            <li><%= link_to "View your profile", user_path(current_user) %></li>
            <li><a href="https://cleveland-portfolio-rails.herokuapp.com/" target="_blank">Portfolio</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="http://codepen.io/cwilliams3579/" target="_blank">CodePen</a></li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "Log in", login_path %></li>
        <li><%= link_to "Sign up", signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Blogger Spot" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Blogger Spot" %>">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= render 'layouts/navigation' %>
  </header>
  <div class="container">

    <%= render 'layouts/messages' %>
    <div class="bottom">
    </div>
    <%= yield %>

    </div>

    <%#= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3 class="text-center">Built using Ruby on Rails and Twitter bootstrap.</h3>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title">
          <%= pluralize(obj.errors.count, "error") %>
          prohibited this article from being saved:
        </h2>
        <div class="panel-body">
          <ul>
            <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/users/_form.html.erb
<%= render 'layouts/messages', obj: @user %>
<% provide(:title, "Edit profile") %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>

    <%= f.label :user_name %>
    <%= f.text_field :username, class: 'form-control', placeholder: "Enter username", autofocus: true %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control', placeholder: "johndoe@gmail.com" %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-primary btn-lg btn-block", id: "edit-btn", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Processing..."}) %>
    <% end %>
  </div>
</div>
<div class="text-center" id="edit-cancel">
  [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
</div>

app/views/users/edit.html.erb
<%= render 'layouts/messages', obj: @user %>
<h1 class="text-center">Edit Article</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center">Bloggers</h1>
<div class="text-center">
  <div class="text-center">
    <%= will_paginate %>
  </div>
  <% @users.each do |user|  %>
  <ul class="listing">
    <div class="row">
      <div class="well col-md-4 col-md-offset-4">
        <li><%= link_to gravatar_for(user), user_path(user) %></li>
        <li class="article-title">
          <%= link_to user.username, user_path(user) %>
        </li>
        <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
        <% if logged_in? and current_user.admin? %>
          <li><%= link_to "Delete this user", user_path(user), method: :delete, data: { confirm: "Are you sure you want to perform this action?"} %></li>
        <% end %>
      </div>
    </div>
  </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<%= render 'shared/errors', obj: @user %>
<h1 class="text-center">Signup for Blogger Spot</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center">Welcome to <%= @user.username %>'s page</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>
<h4 class="text-center"><%= @user.username %>'s articles</h4>
<div class="text-center">
  <%= will_paginate @user_articles %>
</div>
<%= render 'articles/article', obj: @user_articles %>
<div class="text-center">
  <%= will_paginate @user_articles %>
</div>

app/views/visitors/index.html.erb
<div class="container">
<% @articles.each do |a| %>
    <!--Main layout-->
    <div class="container">
        <div class="row">

            <!--Main column-->
            <div class="col-lg-8">

                <!--Post-->
                <div class="post-wrapper">
                    <!--Post data-->
                    <h1 class="h1-responsive"><%= link_to a.title, article_path(a) %></h1>
                    <h3 id="author">Written by <%= a.user.username if a.user %></h3> <h4 id="time"> <%= time_ago_in_words(a.created_at) %> ago</h4>
                    <br>
                    <!--Featured image -->
                    <div class="view overlay hm-white-light z-depth-1-half">
                        <img src="http://mdbootstrap.com/img/Photos/Slides/img%20(22).jpg" class="img-fluid " alt="">
                        <div class="mask">
                        </div>
                    </div>

                    <br>

                    <!--Post excerpt-->
                    <p><%= truncate(a.description, length: 400) %></p>
                    <!--"Read more" button-->
                    <button class="btn btn-primary">Read more</button>
                </div>
                <!--/.Post-->
                <br><br>
                <hr>

            </div>
            <!--Sidebar-->
            <div class="col-lg-4">
              <% if a.categories.any? %>
                <div class="widget-wrapper">
                    <h4>Categories:</h4>
                    <br>
                    <div class="list-group">
                        <%= render a.categories %>
                    </div>
                </div>
                <% end %>


                <!-- <div class="widget-wrapper">
                    <h4>Subscription form:</h4>
                    <br>
                    <div class="card">
                        <div class="card-block">
                            <p><strong>Subscribe to our newsletter</strong></p>
                            <p>Once a week we will send you a summary of the most useful news</p>
                            <div class="md-form">
                                <i class="fa fa-user prefix"></i>
                                <input type="text" id="form1" class="form-control">
                                <label for="form1">Your name</label>
                            </div>
                            <div class="md-form">
                                <i class="fa fa-envelope prefix"></i>
                                <input type="text" id="form2" class="form-control">
                                <label for="form2">Your email</label>
                            </div>
                            <button class="btn btn-primary">Submit</button>

                        </div>
                    </div>
                </div>

            </div> -->
            <!--/.Sidebar-->
        </div>
    </div>
    <!--/.Main layout-->

</div>
<% end %>
<!--Pagination-->
<nav class="text-xs-center">
    <p><%#= will_paginate %></p>
</nav>
<!--/.Pagination-->
<!--Footer-->